spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://api.dev.jdon.kr/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email
          github:
            client-name: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: https://api.dev.jdon.kr/login/oauth2/code/github
            scope: user:email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    web:
      pageable:
        max-page-size: 100
    redis:
      port: 6379
      host: 127.0.0.1
      password: ${REDIS_PASSWORD}


logging:
  level:
    root: info
  slack:
    webhook-uri: ${SLACK_WEBHOOK_URL}
  config: classpath:logback-spring.xml

decorator:
  datasource:
    p6spy:
      enable-logging: true

custom-oauth2:
  kakao:
    app-admin-key: ${KAKAO_APP_ADMIN_KEY}
    delete-user-url: https://kapi.kakao.com/v1/user/unlink

allowed-origins:
  origin: https://dev.jdon.kr/
  url-list:
    - "https://dev.jdon.kr"
    - "https://localhost:3000"

  ip:
    monitoring-list:
      - "3.34.69.116"
      - "0:0:0:0:0:0:0:1"

redirect-url:
  login:
    success:
      member: https://dev.jdon.kr/oauth/login/success
      guest: https://dev.jdon.kr/oauth/info?
    failure:
      not-found-email: https://dev.jdon.kr/oauth/login/fail/not-found-email
      not-match-provider: https://dev.jdon.kr/oauth/login/fail/not-match-provider
      another-withdraw-account: https://dev.jdon.kr/oauth/login/fail/another-withdraw-account
      already-withdraw-account: https://dev.jdon.kr/oauth/login/fail/already-withdraw-account

redis:
  lock:
    coffee-chat:
      wait-time: 5
      lease-time: 1

crypto:
  aes-private-key: ${AES_PRIVATE_KEY}
  hmac-private-key: ${HMAC_PRIVATE_KEY}

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
server:
  tomcat:
    threads:
      min-spare: 20
    mbeanregistry:
      enabled: true