spring:
  config:
    activate:
      on-profile: prod
    import:
      optional:classpath:/constant/scraping.yml

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password: ${REDIS_PASSWORD}

logging:
  level:
    root: info
  slack:
    webhook-uri: ${SLACK_WEBHOOK_URL}
  config: classpath:logback-spring.xml

decorator:
  datasource:
    p6spy:
      enable-logging: true

scraping:
  inflearn:
    url: https://www.inflearn.com/courses
    detail_url_prefix: https://www.inflearn.com
    max_courses_per_keyword: 3
    max_courses_per_page: 24
    sleep: # 단위 millis
      min_initial: 1000
      max_initial: 3000
      max: 10000
      increment: 1000
